-- 1. 학과 이름과 계열 표시
SELECT DEPARTMENT_NAME as "학과명", CATEGORY as "계열"
FROM TB_DEPARTMENT;

-- 2. 학과 정원 출력
SELECT DEPARTMENT_NAME ||'의 정원은 ' || CAPACITY || '명 입니다.' as "학과별 정원" FROM TB_DEPARTMENT;

-- 3. 특정 데이터 찾기 (논리, LIKE)
SELECT DEPARTMENT_NAME as "학과명", DEPARTMENT_NO as "학과번호" FROM TB_DEPARTMENT;
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE ABSENCE_YN='Y' AND DEPARTMENT_NO=001 AND STUDENT_SSN LIKE '_______2%';

-- 4. 특정 데이터 찾기 (IN)
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119');

-- 5. 범위 찾기
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

-- 6. 특정 데이터 찾기 (IS NULL)
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

-- 7. 특정 데이터 찾기 (IS NULL)
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

-- 8. 특정 데이터 찾기 (NOT NULL)
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9. 중복 제거
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT;

-- 10. 특정 데이터 출력 (논리, 날짜 비교, LIKE)
SELECT STUDENT_ADDRESS, ENTRANCE_DATE FROM TB_STUDENT;
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN='N' AND ENTRANCE_DATE>'02/01/01' AND ENTRANCE_DATE<'03/01/01' AND STUDENT_ADDRESS LIKE '전주%';
